### ISSUE TITLE
How to handle multimodule projects?

### ISSUE THREAD

**Issue by surli** [monperrus/bears-specification#3]
You say:

> This PR must contain at least:
>  - a well-formed Maven file called pom.xml at the root of the branch

Does it mean:
  1. That the branch does not contain necessarily source code?
  2. That the branch does not necessarily reflect the true organization of the original project the bug comes from? 

For 1. my question is pretty clear: do you plan to put source code in each bug branch?
For 2. my question is essentially about proposing branch automatically: a lot of projects contains pom.xml which are not necessarily in the root directory of the project. So we'll need to process the project file to format it to your need: is that true?
Isn't it easier to simply keep the original repository organization and then document the path of the pom.xml used? 

Another question: what about bugs using gradle instead of maven? We don't want to process them at all?

**Comment by monperrus** [comment]
> For 1. my question is pretty clear: do you plan to put source code in each bug branch?
yes, see 1ddf2ddcbd037ac7ee61a7e09051efb78484bf51

**Comment by monperrus** [comment]
> Another question: what about bugs using gradle instead of maven? We don't want to process them at all?

See https://github.com/monperrus/bears-specification/issues/4

**Comment by monperrus** [comment]
> For 2. my question is essentially about proposing branch automatically: a lot of projects contains
> pom.xml which are not necessarily in the root directory of the project. 
the goal is to do "git fetch <repo> 0001; mvn test" so there must be a pom.xml at the root.

There is the question of multimodule projects.

WDYT?

**Comment by surli** [comment]
> the goal is to do "git fetch <repo> 0001; mvn test" so there must be a pom.xml at the root.

Or you can do "git fetch <repo> 0001; ./mvnw test" and mvnw would be something like: 

`cd ./patch/to/pom.xml && mvn test`

It avoids changing the organization of the repo, and keeps the usage of a simple script.

**Comment by tdurieux** [comment]
I would see to keep the complete multi-module project.

**Comment by monperrus** [comment]
what do you think of adding a property in the json file "path_to_pom.xml"

this property is optional and defaults to "./pom.xml"

**Comment by tdurieux** [comment]
not a big fan, because it encodes deeply maven usage.
I would like to stay open to other build systems even if we focus on maven in the beginning.

**Comment by monperrus** [comment]
what's the alternative?

this does not prevent us to add other properties later/

**Comment by tdurieux** [comment]
What is the problem to keep the multi-module project and just use the parent pom.xml.
I would say also to add the build system type in the metadata of the bug.

**Comment by surli** [comment]
In fact for multimodule we can use something like:

`mvn surefire-report:report -Daggregate=true -fae`

with the root pom.xml.

My question was not about multi module.

**Comment by monperrus** [comment]
OK, so for multimodule we always assume a root pom.

Your question is if the root folder is not even a Maven folder? Then we would need "path_to_pom.xml" ?

**Comment by surli** [comment]
> Your question is if the root folder is not even a Maven folder?

Exactly. I cannot find it right now but we have some projects with a messy organization like this in Repairnator.

**Comment by tdurieux** [comment]
Personally, I would exclude them.

**Comment by monperrus** [comment]
You're right, this happens.

I would exclude them as well, and always assume a root pom.xml, either a 
normal one, or a parent in multimodule projects.

OK for you?

**Comment by surli** [comment]
> OK for you?

Absolutely!
